

server:
  port: 9001  # The Accounts microservice runs on port 9000


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/session2
    username: root
    password: 682000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

applications:
  name: "accounts"
server:
  port: 8080

build:
  version: "3.0"

  config:
    import:
      - "accounts_qa.yml"
      - "accounts_prod.yml"
    profiles:
      active:
        - "prod"
